plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/root/Projects/replay/replay/site"
publishOrigin = "config"
base = "/root/Projects/replay/replay/site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]